### ISSUE TITLE
Reporte de Entrevista

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-jad#1]
[Reporte_de_ENTREVISTA JAD.pdf](https://github.com/user-attachments/files/16858318/Reporte_de_ENTREVISTA.JAD.pdf)
Entrevista Realizada por:
Jaczibeth Cruz Ramirez 
Kevin Andrew Osorio Aparicio 
Daniel Velasco López

**Comment by MarleneRamirez0731** [comment]
Cubre el 20% de acuerdo a la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
